services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: bookstore_db
    ports:
      - "5433:5432"
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://test:test@db:5432/bookstore_db
  
  test:
    extends: app
    command: ["poetry", "run", "pytest"]
